In [13]:
import pandas as pd

#Cargar el archivo CSV tratado

In [14]:

df = pd.read_csv("datos_tratados/datos_tratados_TelecomXParte2.csv")
df.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total,Cuentas_Diarias
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,0,1,1,0,One year,1,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,0,0,0,1,Month-to-month,0,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,1,0,0,0,Month-to-month,1,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,1,0,1,1,Month-to-month,1,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,0,1,1,0,Month-to-month,1,Mailed check,83.9,267.40,2.796667

#Verificación rápida: estructura, tipos y nulos

In [15]:
df.shape

(7032, 22)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   Churn             7032 non-null   int64
 2   gender            7032 non-null   object
 3   SeniorCitizen     7032 non-null   int64
 4   Partner           7032 non-null   int64
 5   Dependents        7032 non-null   int64
 6   tenure            7032 non-null   int64
 7   PhoneService      7032 non-null   int64
 8   MultipleLines     7032 non-null   object
 9   InternetService   7032 non-null   object
 10  OnlineSecurity    7032 non-null   int64
 11  OnlineBackup      7032 non-null   int64
 12  DeviceProtection  7032 non-null   int64
 13  TechSupport       7032 non-null   int64
 14  StreamingTV       7032 non-null   int64
 15  StreamingMovies   7032 non-null   int64
 16  Contract          7032 non-null   object
 17  PaperlessBilling  7032 non-null   int64
 18  PaymentMethod     7032 non-null   object
 19  Charges.Monthly   7032 non-null   float64
 20  Charges.Total     7032 non-null   float64
 21  Cuentas_Diarias   7032 non-null   float64
dtypes: float64(3), int64(13), object(6)
memory usage: 1.2+ MB

In [17]:
# Nulos (top 15)
df.isna().sum().sort_values(ascending=False).head(15)

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
dtype: int64

In [18]:
df["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [19]:
df["Churn"].value_counts(normalize=True) * 100

Churn
0    73.421502
1    26.578498
Name: proportion, dtype: float64

In [20]:
df.columns

Index(['customerID', 'Churn', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'tenure', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly', 'Charges.Total',
       'Cuentas_Diarias'],
      dtype='object')

In [21]:
df.dtypes

customerID           object
Churn                 int64
gender               object
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines        object
InternetService      object
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract             object
PaperlessBilling      int64
PaymentMethod        object
Charges.Monthly     float64
Charges.Total       float64
Cuentas_Diarias     float64
dtype: object

#Eliminación de Columnas Irrelevantes

In [22]:
#Eliminando CustomerID
df_modelo = df.drop(columns=["customerID"])
df_modelo.columns

Index(['Churn', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'Charges.Monthly', 'Charges.Total', 'Cuentas_Diarias'],
      dtype='object')

In [23]:
#Eliminando cuentas_diarias
df_modelo = df_modelo.drop(columns=["Cuentas_Diarias"])
df_modelo.columns

Index(['Churn', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'Charges.Monthly', 'Charges.Total'],
      dtype='object')

In [26]:
#Meto una verificación para estar seguro
print("Columnas finales para modelado:", df_modelo.columns.tolist())
print("¿customerID sigue?", "customerID" in df_modelo.columns)

Columnas finales para modelado: ['Churn', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Charges.Monthly', 'Charges.Total']
¿customerID sigue? False